spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mynews?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: X8y$Z9a@B3
  redis:
    host: localhost           # Redis服务器地址
    port: 6379               # Redis服务器端口
    database: 0              # 使用的数据库索引，默认是0
    password:                # Redis服务器密码，如果没有设置可以为空
    timeout: 10000          # 连接超时时间（毫秒）
    lettuce:                # 使用lettuce连接池
      pool:
        max-active: 8       # 连接池最大连接数
        max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: INFO
    com.example.mynews: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mynews.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
crawler:
  sites:
    - name: "新华网"
      baseUrl: "http://www.news.cn"
      listUrl: "/politics/"  # 政治新闻频道
      headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
        Accept-Language: "zh-CN,zh;q=0.9"
        Connection: "keep-alive"
      listSelector: "div.gridContent ul.newList01 li"  # 新闻列表选择器
      titleSelector: "div.h-title"  # 标题选择器
      contentSelector: "div#detail"  # 正文选择器
      dateSelector: "div.h-info span.h-time"  # 日期选择器
      crawlInterval: 30  # 爬取间隔(分钟)
    # 可以添加新华网的其他频道
    - name: "新华网-国际"
      baseUrl: "http://www.news.cn"
      listUrl: "/world/"
      headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
        Accept-Language: "zh-CN,zh;q=0.9"
        Connection: "keep-alive"
      listSelector: "div.gridContent ul.newList01 li"
      titleSelector: "div.h-title"
      contentSelector: "div#detail"
      dateSelector: "div.h-info span.h-time"
      crawlInterval: 30
management:
  endpoints:
    web:
      exposure:
        include: health,info  # 暴露健康检查和信息端点
  endpoint:
    health:
      show-details: always   # 显示详细的健康检查信息